### PR TITLE
Add CocoaPods support

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by norio-nomura** [comment]
Reopen it to start CI.

**Comment by ikesyo** [comment]
Is  CircleCI disabled relating to #25?

**Comment by norio-nomura** [comment]
It was disabled on preparing [the deprecation of GitHub Services](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) by me. It has been enabled again as GitHub Apps.

**Comment by norio-nomura** [comment]
Thanks for contribution! 🙏

**Comment by norio-nomura** [comment]
```terminal.sh-session
$ pod trunk push

[!] Found podspec `ObjectEncoder.podspec`
Updating spec repo `master`
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 42414 and retry the command.
Validating podspec
 -> ObjectEncoder (0.2.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  ObjectEncoder (0.2.0) successfully published
 📅  January 2nd, 22:50
 🌎  https://cocoapods.org/pods/ObjectEncoder
 👍  Tell your friends!
--------------------------------------------------------------------------------
pod trunk push  37.81s user 62.20s system 36% cpu 4:35.28 total
```

**Pull request merged**
